name: Builder (Linux)

on:
  workflow_call:
    inputs:
      arch:
        description: Architecture to build for (x86_64, arm64)
        type: string
        default: x86_64
      output_name:
        description: Output name
        type: string
        default: PluginLoader

jobs:
  build:
    name: Build ${{ inputs.output_name }} (Linux ${{ inputs.arch }})
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-22.04' }}

    steps:
    - name: Checkout 🧰
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up NodeJS 20 💎
      uses: actions/setup-node@v4
      with:
        node-version: 20
      
    - name: Set up Python 3.11.7 🐍
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.7"
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    - name: Install Python dependencies ⬇️
      working-directory: ./backend
      run: |
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry install --no-interaction

    - name: Install JS dependencies ⬇️
      working-directory: ./frontend
      run: |
        npm i -g pnpm
        pnpm i --frozen-lockfile --dangerously-allow-all-builds

    - name: Build JS Frontend 🛠️
      working-directory: ./frontend
      run: pnpm run build

    - name: Build Python Backend 🛠️
      working-directory: ./backend
      run: |
        poetry dynamic-versioning 
        pyinstaller pyinstaller.spec

    - name: Rename artifact 🛠️
      if: ${{ inputs.output_name != 'PluginLoader' }}
      run: mv ./backend/dist/PluginLoader ./backend/dist/${{ inputs.output_name }}

    - name: Upload package artifact ⬆️
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output_name }}
        path: ./backend/dist/${{ inputs.output_name }}

    - name: Download package artifact locally
      if: ${{ env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        path: ./backend/dist/${{ inputs.output_name }}
