name: Type Check

on:
  push:
  pull_request:

jobs:
  typecheck:
    name: Run type checkers
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7 # Check out the repository first.

      - name: Set up NodeJS LTS 💎
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"

      - name: Set up Python 3.11 🐍
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install Python dependencies ⬇️
        working-directory: backend
        run: poetry install --no-interaction

      - name: Install TypeScript dependencies
        working-directory: frontend
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile --dangerously-allow-all-builds

      - name: Run pyright (Python)
        uses: jakebailey/pyright-action@v3
        with:
          python-version: "3.10.6"
          annotate: "none"
          working-directory: backend

      - name: Run tsc (TypeScript)
        working-directory: frontend
        run: pnpm run typecheck